/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/anchor/deposit": {
    /**
     * Start anchor deposit flow
     * @description Protected route. Starts a fiat -> USDC flow against the configured anchor.
     * Returns a URL and/or flow steps. Returns 501 when anchor is not configured.
     */
    post: {
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
  "/health": {
    /**
     * Health check
     * @description Returns system status and connectivity for RPC, DB, and optional anchor.
     */
    get: {
      responses: {
        /** @description All critical dependencies are healthy. */
        200: {
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
        /** @description One or more critical dependencies are unhealthy. */
        503: {
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
      };
    };
  };
  "/remittance/quote": {
    /** Get Remittance Quote */
    get: {
      parameters: {
        query: {
          /**
           * @description Amount to send (> 0)
           * @example 100.5
           */
          amount: number;
          /**
           * @description 3-letter ISO code
           * @example USD
           */
          currency: string;
          /**
           * @description 3-letter ISO code
           * @example PHP
           */
          toCurrency: string;
        };
      };
      responses: {
        /** @description Quote successful */
        200: {
          content: {
            "application/json": components["schemas"]["RemittanceQuoteResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/remittance/build": {
    /** Build Remittance Transaction */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["BuildRemittanceRequest"];
        };
      };
      responses: {
        /** @description Transaction built */
        200: {
          content: {
            "application/json": components["schemas"]["BuildRemittanceResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/remittance/history": {
    /** Get Remittance History */
    get: {
      parameters: {
        query?: {
          /** @example 20 */
          limit?: number;
          cursor?: string;
          /** @example completed */
          status?: "completed" | "failed" | "pending";
        };
      };
      responses: {
        /** @description History records */
        200: {
          content: {
            "application/json": components["schemas"]["RemittanceHistoryResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/remittance/status/{txHash}": {
    /** Get Remittance Status */
    get: {
      parameters: {
        path: {
          /** @example d41d8cd98f00b204e9800998ecf8427e */
          txHash: string;
        };
      };
      responses: {
        /** @description Transaction status */
        200: {
          content: {
            "application/json": components["schemas"]["RemittanceStatusResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/split/calculate": {
    /** Calculate Split Allocation */
    get: {
      parameters: {
        query: {
          /**
           * @description Amount to split (> 0)
           * @example 1000
           */
          amount: number;
        };
      };
      responses: {
        /** @description Calculated allocations */
        200: {
          content: {
            "application/json": components["schemas"]["SplitCalculateResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/split/initialize": {
    /** Initialize Split Configuration */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SplitPercentages"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["SplitUpdateResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/split/update": {
    /** Update Split Configuration */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SplitPercentages"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["SplitUpdateResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/bills": {
    /** Create a new Bill */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateBillRequest"];
        };
      };
      responses: {
        /** @description XDR for transaction */
        200: {
          content: {
            "application/json": components["schemas"]["XdrResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/bills/{id}/pay": {
    /** Pay a Bill */
    post: {
      parameters: {
        path: {
          /** @example bill_123456 */
          id: string;
        };
      };
      responses: {
        /** @description XDR to pay bill */
        200: {
          content: {
            "application/json": components["schemas"]["XdrResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/bills/{id}/cancel": {
    /** Cancel a Bill */
    post: {
      parameters: {
        header?: {
          "x-owner-only"?: string;
          "x-owner"?: string;
        };
        path: {
          /** @example bill_123456 */
          id: string;
        };
      };
      responses: {
        /** @description XDR to cancel bill */
        200: {
          content: {
            "application/json": components["schemas"]["XdrResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/bills/due-soon": {
    /** Get bills due soon */
    get: {
      responses: {
        /** @description List of bills due within 7 days */
        200: {
          content: {
            "application/json": components["schemas"]["BillDueSoon"][];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/insurance": {
    /** Create Insurance Policy */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateInsuranceRequest"];
        };
      };
      responses: {
        /** @description Returns XDR */
        200: {
          content: {
            "application/json": components["schemas"]["XdrResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/insurance/{id}/pay": {
    /** Pay Insurance Premium */
    post: {
      parameters: {
        path: {
          /** @example ins_7890 */
          id: string;
        };
      };
      responses: {
        /** @description Returns XDR */
        200: {
          content: {
            "application/json": components["schemas"]["XdrResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/insurance/{id}/deactivate": {
    /** Deactivate Insurance Policy */
    post: {
      parameters: {
        header?: {
          "x-owner-only"?: string;
          "x-owner"?: string;
        };
        path: {
          /** @example ins_7890 */
          id: string;
        };
      };
      responses: {
        /** @description Returns XDR */
        200: {
          content: {
            "application/json": components["schemas"]["XdrResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/admin/audit": {
    /** List audit events */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
      };
      responses: {
        /** @description Audit events */
        200: {
          content: {
            "application/json": {
              events?: Record<string, never>[];
            };
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/admin/users": {
    /** List recent users */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
      };
      responses: {
        /** @description User list */
        200: {
          content: {
            "application/json": {
              users?: Record<string, never>[];
            };
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/v1/admin/webhooks/dlq": {
    /** List Webhook DLQ */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number;
          /** @example stripe */
          source?: string;
        };
      };
      responses: {
        /** @description DLQ events */
        200: {
          content: {
            "application/json": components["schemas"]["WebhookDlqResponse"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApiError: {
      /**
       * @description A translated error message based on the Accept-Language header.
       * If the translation is missing or language is not supported, defaults to English.
       * Example translations:
       *  - en: "Unauthorized: missing or invalid x-user header"
       *  - es: "No autorizado: falta o es inválido el encabezado x-user"
       *
       * @example Unauthorized: missing or invalid x-user header
       */
      error?: string;
    };
    HealthStatus: {
      /**
       * @example ok
       * @enum {string}
       */
      status?: "ok" | "unhealthy";
      /**
       * @example ok
       * @enum {string}
       */
      database?: "ok" | "error";
      /**
       * @example ok
       * @enum {string}
       */
      rpc?: "ok" | "error";
      /**
       * @example ok
       * @enum {string}
       */
      anchor?: "ok" | "error" | "skipped";
    };
    RemittanceQuoteResponse: {
      /** @example 100 */
      sendAmount?: number;
      /** @example 5600.5 */
      receiveAmount?: number;
      /** @example 1.5 */
      fee?: number;
      /** @example 56 */
      rate?: number;
      /**
       * Format: date-time
       * @example 2023-10-12T07:20:50.52Z
       */
      expiry?: string;
      /**
       * @example anchor
       * @enum {string}
       */
      source?: "anchor" | "stellar";
    };
    BuildRemittanceRequest: {
      /** @example 250 */
      amount: number;
      /**
       * @default USDC
       * @example USDC
       */
      currency?: string;
      /** @example GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5 */
      recipientAddress: string;
      /** @example Monthly support */
      memo?: string;
    };
    BuildRemittanceResponse: {
      /** @example AAAAAgAAAAA... */
      xdr?: string;
      /** @example Test SDF Network ; September 2015 */
      networkPassphrase?: string;
      simulate?: {
        /** @example 100 */
        fee?: string;
        /** @example true */
        success?: boolean;
      };
    };
    RemittanceHistoryResponse: {
      /** @example GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5 */
      userAddress?: string;
      [key: string]: unknown;
    };
    RemittanceStatusResponse: {
      /** @example d41d8cd98f00b204e9800998ecf8427e */
      hash?: string;
      status?: {
        [key: string]: unknown;
      };
    };
    SplitCalculateResponse: {
      /**
       * @example {
       *   "savings": 300,
       *   "bills": 200,
       *   "insurance": 50
       * }
       */
      amounts?: {
        [key: string]: unknown;
      };
    };
    SplitPercentages: {
      /** @example 50 */
      spending: number;
      /** @example 25 */
      savings: number;
      /** @example 20 */
      bills: number;
      /** @example 5 */
      insurance: number;
    };
    SplitUpdateResponse: {
      /** @example true */
      success?: boolean;
      /** @example AAAAAgAAAAA... */
      xdr?: string;
      simulate?: {
        [key: string]: unknown;
      };
      /** @example Successfully updated split percentages */
      message?: string;
    };
    CreateBillRequest: {
      /** @example Electric Bill */
      name: string;
      /** @example 120.5 */
      amount: number;
      /**
       * Format: date-time
       * @example 2023-10-15T00:00:00Z
       */
      dueDate: string;
      /**
       * @default false
       * @example true
       */
      recurring?: boolean;
      /** @example 30 */
      frequencyDays?: number;
    };
    XdrResponse: {
      /** @example AAAAAgAAAAA... */
      xdr?: string;
    };
    BillDueSoon: {
      /** @example bill_123456 */
      billId: string;
      /** @example Electric Bill */
      name: string;
      /** @example 120.5 */
      amount: number;
      /**
       * Format: date-time
       * @example 2023-10-15T00:00:00Z
       */
      dueDate: string;
    };
    CreateInsuranceRequest: {
      /** @example Health Insurance */
      name: string;
      /** @example Medical */
      coverageType: string;
      /** @example 250 */
      monthlyPremium: number;
      /** @example 100000 */
      coverageAmount: number;
    };
    WebhookDlqResponse: {
      /** @example true */
      success?: boolean;
      data?: {
        events?: Record<string, never>[];
        pagination?: {
          /** @example 50 */
          limit?: number;
          /** @example 0 */
          offset?: number;
          /** @example 5 */
          total?: number;
          /** @example false */
          hasMore?: boolean;
        };
        /**
         * @example {
         *   "pending": 0,
         *   "processing": 0,
         *   "processed": 100,
         *   "failed": 5,
         *   "dlq": 5,
         *   "total": 110
         * }
         */
        stats?: Record<string, never>;
      };
    };
  };
  responses: never;
  parameters: {
    /** @description Optional header to request localized responses. Supported languages: 'en' (English), 'es' (Spanish). */
    AcceptLanguageHeader?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
